kind: pipeline
name: default

steps:
  # - name: publish-amd
  #   image: plugins/docker
  #   settings:
  #     auto_tag: true
  #     auto_tag_suffix: linux-amd64
  #     dockerfile: Dockerfile
  #     username:
  #       from_secret: docker_username
  #     password:
  #       from_secret: docker_password
  #     repo: alexphillips/shoutout-board
  #   when:
  #     event:
  #       - push
  #       - tag

  - name: download-qemu
    image: golang:1.10
    pull: true
    commands:
      - GOARCH=amd64 QEMU_ARCH=amd64 make docker-download-qemu-binary
      - GOARCH=arm QEMU_ARCH=arm make docker-download-qemu-binary
      - GOARCH=arm64 QEMU_ARCH=aarch64 make docker-download-qemu-binary
    when:
      event:
        - push
        - tag

  - name: register-qemu
    image: multiarch/qemu-user-static:register
    pull: true
    privileged: true
    commands:
      - /register --reset
    when:
      event:
        - push
        - tag

  - name: publish-arm
    image: plugins/docker
    settings:
      auto_tag: true
      auto_tag_suffix: linux-arm
      dockerfile: Dockerfile.arm
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: alexphillips/shoutout-board
      build_args:
        -- TARGET=arm32v6
    when:
      event:
        - push
        - tag

  # docker-setup:
  #   image: golang:1.10
  #   pull: true
  #   commands:
  #     - GOARCH=amd64 QEMU_ARCH=amd64 make docker-download-qemu-binary
  #     - GOARCH=arm QEMU_ARCH=arm make docker-download-qemu-binary
  #     - GOARCH=arm64 QEMU_ARCH=aarch64 make docker-download-qemu-binary
  #   when:
  #     event: [ push, tag ]
  # docker-qemu-dl:
  #   image: multiarch/qemu-user-static:register
  #   pull: true
  #   privileged: true
  #   when:
  #     event: [ push, tag ]
  # docker-amd:
  #   image: plugins/docker
  #   pull: true
  #   secrets: [ docker_username, docker_password ]
  #   group: docker
  #   repo: alexphillips/shoutout-board
  #   tag: 'latest-linux-amd64'
  #   build_args:
  #     - TARGET=amd64
  #   dockerfile: Dockerfile
  #   when:
  #     event: [ push, tag ]
  # docker-arm:
  #   image: plugins/docker
  #   pull: true
  #   secrets: [ docker_username, docker_password ]
  #   group: docker
  #   repo: alexphillips/shoutout-board
  #   tag: 'latest-linux-arm'
  #   build_args:
  #     - TARGET=arm32v6
  #   dockerfile: Dockerfile.arm
  #   when:
  #     event: [ push, tag ]
  # # docker:
  # #   image: plugins/docker:17.12
  # #   pull: true
  # #   secrets: [ docker_username, docker_password ]
  # #   group: docker
  # #   repo: gitea/gitea
  # #   tag: 'latest-linux-arm64'
  # #   build_args:
  # #     - TARGET=arm64v8
  # #   dockerfile: docker/Dockerfile.aarch64
  # #   when:
  # #     event: [ push, tag ]
