FROM lsiobase/alpine:3.8

COPY qemu-arm-static /usr/bin/
COPY . /app

RUN \
 apk update && \
 apk add nodejs npm && \
 cd /app && \
 npm install --no-dev && \
 cd pwa && \
 npm install --no-dev && \
 npm run build-prod && \
 cd ..

WORKDIR /app

CMD [ "/usr/local/bin/npm", "start" ]
